### ISSUE TITLE
Player head is dropping upon death

### ISSUE THREAD

**Issue by mikeauen** [MLDEG/AllMobHeads#10]
### Datapack version

10.0.1

### Description

When a player dies by game mechanics, by drowning for example, the player is dropping their head. I do not have any player head mods/dps on the system. When I disable this mod, the player heads do not drop any more. The player head does NOT have a "killed by" tag on it, so it is not registering that a player damaged the dead player for the kill.

I do not want a player head to drop every time a player dies.
Is this a setting that can be disabled, or is this a bug?

### Steps to reproduce

Enable this datapack.
Walk player into water and wait to die to drowning.
player head is dropped where the player died.

### Expected behavior

Player dies and does not drop a player head.

**Comment by MLDEG** [comment]
I see, I'll add the Killed by player condition in an upcoming fix this week.

**Comment by MLDEG** [comment]
Fix :)
https://www.curseforge.com/minecraft/customization/all-mob-heads/files/5481077

**Comment by mikeauen** [comment]
Tested the fix!  Thanks so much!! :)
