### ISSUE TITLE
Colorful dog heads

### ISSUE THREAD

**Issue by 1robie** [MLDEG/AllMobHeads#11]
### Datapack version

10.0.1

### Description

Hello, when I tame a wolf and put dye on it it just drops the dog's head and not the one corresponding to its color. Thank you and have a nice evening/day

### Steps to reproduce

- Taming a wolf
- using dye on our dog
- kill the dog

### Expected behavior

This should drop a dog head from the dog's birth biome with the color of its collar, but it only drops a dog head without the collar color.

**Comment by MLDEG** [comment]
Do you use a Vanilla server ?

**Comment by MLDEG** [comment]
Fix :)
https://www.curseforge.com/minecraft/customization/all-mob-heads/files/5481077
