### ISSUE TITLE
charged creeper head

### ISSUE THREAD

**Issue by Techn0driv3r** [MLDEG/AllMobHeads#12]
### Datapack version

V10.2

### Description

Me and my friend are working on collecting all the heads but weve been trying to get the charged creeper head and ended up killing 7 charged creepers none dropping their head even though on the achievement page says its a 100%  Were just curious what would help or if its a bug 

### Steps to reproduce

1. I charge the creeper with a trident with the enchantment channeling 
2. the creeper gets struck by lightning and becomes charged
3. i kill said creeper but the head doesnt drop

### Expected behavior

the head should drop as intended

**Comment by MLDEG** [comment]
Hi !
In my test world I was able to drop the head without any weapons and therefore no looting.
You must not use a vanilla server or there may be another datapack which is creating a problem with mine ?
