### ISSUE TITLE
Slime head don't drop

### ISSUE THREAD

**Issue by Shark10199** [MLDEG/AllMobHeads#13]
### Datapack version

v10.2 - 1.21

### Description

With looting on my sword, I killed thousands of slimes and still don't have the head.

### Steps to reproduce

Kill

### Expected behavior

Head

**Comment by MLDEG** [comment]
I assume you are not playing single player but on a server that is not vanilla?

**Comment by Shark10199** [comment]
I tested it in a local world. Not a server.

**Comment by MLDEG** [comment]
I tested it and it works :)
![2024-07-27_21 41 19](https://github.com/user-attachments/assets/2db81db6-2ded-4343-8525-512bb5c9cb4f)
