### ISSUE TITLE
Advancement Armadillo

### ISSUE THREAD

**Issue by Neiddybouh** [MLDEG/AllMobHeads#3]
### Datapack version

9.0

### Description

L'Armadillo ne possède pas d'advancement qui lui est propre, il compte bien dans la liste de collection totale cependant (pour ses 2 variantes)

### Steps to reproduce

Lorsque j'ai tué et obtenu la tête de l'armadillo, je n'ai pas eu la notification de l'obtention de l'advancement. J'ai donc été vérifié dans mes advancements et je n'ai vu nul part que la tête était obtenue, cependant, ça l'a bien ajoutée dans la collection complète des têtes obtenues.

### Expected behavior

Notification de l'obtention de la tête de l'Armadillo (Sous ses 2 variantes) et ajout de celles-ci dans 2 cases respectives dans la liste d'advancements

**Comment by MLDEG** [comment]
Merci du report, je fait une update rapidement :)
