### ISSUE TITLE
loot têtes renomée

### ISSUE THREAD

**Issue by LalyMary** [MLDEG/AllMobHeads#4]
### Datapack version

1.20.1

### Description

j'ai essayer avec des slimes renommés avec une couleur (red) je n'ai obtenus qu'une tête classique. 
j'ai essayer avec des schulkers renomées avec des couleurs je n'ai obtenus qu'une tête classique.
j'ai recupéré l'épée de votre description youtube

j'ai éssayé le datapack seul avec forge 1.20.1 il s'installe mais je rencontre le bug.
j'ai éssayer avec la version classique de minecraft 1.20.1 je rencontre le bug...

pourriez vous m'aider ? merci 

### Steps to reproduce

créatif ou survival = je rencontre le bug
name tag renomé avec les couleurs en anglais comme sur la description forge

### Expected behavior

le spawn de la tête renomée du mobs

**Comment by LalyMary** [comment]
j'ai utilisé ' potato ' pour le rename

**Comment by MLDEG** [comment]
Le datapack n'est pas adapté pour les versions forge, fabric, paper etc...
Et la version 1.20.1 n'est plus mise à jour, maintenant les versions à jours sont la 1.20.2 jusqu'à 1.20.5 :)
