### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by luuk-sndr** [MLDEG/AllMobHeads#6]
### Datapack version

1.20.1

### Description

Hi, I just downloaded this datapack and put it into the folder in Modrinth and its not working and I don't know what to do now.

### Steps to reproduce

It's just not working

### Expected behavior

It should work.

### Anything else to note?

I got many mods, but no more datapacks. I don't know if it's just not working with fabric, idk

**Comment by MLDEG** [comment]
You need to use the [V7.3.1](https://legacy.curseforge.com/minecraft/customization/all-mob-heads/files/4586222) in 1.20.1
