### ISSUE TITLE
Les raid captain ne droppent pas d'ominous bottle.

### ISSUE THREAD

**Issue by DjeCkard** [MLDEG/AllMobHeads#7]
### Datapack version

V9.2

### Description

Sur un serveur en 1.20.6 avec les fonctionnalités expérimentales de la 1.21 activées. J'ai remarqué que les raid captain ne lootaient pas d'ominous bottle avec ce datapck installé. 

### Steps to reproduce

les raid captain ne loot pas d'ominous bottle

### Expected behavior

les raids captain devraient loot des ominous bottle

**Comment by MLDEG** [comment]
Même problème qu'ici et pourtant tout fonctionne de mon côté, donc la seule possibilité que je vois, c'est que tu as d'autre datapack ou que tu n'utilises pas de server vanilla.
Si aucun des deux n'est le cas alors, j'ignore totalement d'où peu venir le bug puisque je suis dans l'incapacité de reproduire le bug.

https://github.com/MLDEG/AllMobHeads/issues/5

**Comment by DjeCkard** [comment]
Mon serveur n'est pas vanilla en effet, il est sous Purpur 1.20.6!
Je vais essayer ça comme dis dans l'autre report : "I was able to fix this myself by manually reinserting the Ominous Bottle code into the datapack"

**Comment by MLDEG** [comment]
Bah le problème, c'est que je lui ai posé la question de comment il a fait, car par défaut, il a déjà la loot table correcte pour drop le Ominous Bottle ...
