### ISSUE TITLE
Problème avec les advencements du datapack sur un serveur minestrator.

### ISSUE THREAD

**Issue by e1000ouch** [MLDEG/AllMobHeads#8]
### Datapack version

AllMobHeads_V9.2

### Description

salut, j'ai rencontré un petit problème avec le datapack AllMobHeads que j'ai mis sur un serveur minestrator sur le quel je fais une survie avec des potes.
voila mon problème :

le drop de tête marche bien mais quand on récupère la tête, on n'obtient pas le succès.
le problème ne vient pas du mod parce que j'ai utilisé le même en monde solo et il marche parfaitement.

voila voila, merci d'avance si quelqu'un trouve une solution !

### Steps to reproduce

J'ai mis le datapack au bon endroit car on peut drop les têtes

### Expected behavior

On devrait obtenir le succès quand on récupère les têtes.

**Comment by MLDEG** [comment]
Tu ne doit pas utilisé un server vanilla :)

**Comment by Guitarix1** [comment]
Bonjour, j'ai malheureusement le même problème étant sur serveur bukkit. Il y a-t-il une commande pour enable/disable les advencements?
